[package]
name = "pretty-error-debug"
version = "0.1.1"
authors = ["René Kijewski <crates.io@k6i.de>"]
repository = "https://github.com/Kijewski/pretty-error-debug"
license = "MIT OR Apache-2.0"
edition = "2018"
# rust-version = "1.31"
description = "Write out the `Error` message and chain."

[dependencies]
pretty-error-debug-derive = { version = "0.1.0", optional = true, path = "derive" }

[features]
default = ["derive"]
derive = ["pretty-error-debug-derive"]

[workspace]
members = [".", "derive"]
