[package]
name = "test-shadowed-core"
version = "0.0.0"
license = "MIT OR Apache-2.0"
edition = "2021"
publish = false

[dependencies]
core = { package = "syn", version = "2.0.0" }
test_subject = { version = "*", path = "..", package = "pretty-error-debug" }
